# Generated by Django 5.2 on 2025-08-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0007_event_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
