# Generated by Django 5.2 on 2025-08-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_transaction_event_alter_transaction_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='abn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tfn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
